FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
COPY ./script/run_celery.sh /

# create unprivileged user
RUN adduser --disabled-password --gecos '' appuser
