# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('finished', 'finished'), ('failed', 'failed')], max_length=20),
        ),
    ]
